version: '3.3'

services:
  agent:
    image: agent-service:${TAG}
    volumes:
      - agent-sql:/var/lib/mysql
      - agent-wp:/usr/share/wordpress/wp-content
    networks:
      main-overlay:
        ipv4_address: ${HOST_IP}
    build:
      context: .
      args:
        INTERFACE: ${INTERFACE}
        URL: ${URL}
        HOST_IP: ${HOST_IP}
        LOGSTASH_URI: ${LOGSTASH_URI}
        LOGSTASH_PORT: ${LOGSTASH_PORT}

networks:
  main-overlay:
    external: true

volumes:
  agent-sql:
  agent-wp:
  
