version: '3.3'

services:
  agent:
    image: agent:${TAG}
    volumes:
      - agent-sql:/var/lib/mysql
      - agent-wp:/usr/share/wordpress/wp-content
    networks:
      main-overlay:
        ipv4_address: 10.0.2.98

networks:
  main-overlay:
    external: true

volumes:
  agent-sql:
  agent-wp:
  
