filebeat.inputs:
- type: log
  paths:
    - "/tshark/packets.json"
  document_type: "pcap_file"
  json.keys_under_root: true

- type: log
  paths:
    - "/var/log/apache2/*"
  fields:
    apache: true
  fields_under_root: true

- type: log
  paths:
    - "/var/log/mysql/*"
  fields:
    mysql: true
  fields_under_root: true
  
# - type: filestream
#   enabled: false
#   paths:
#     - /var/log/*.log

# filebeat.config.modules:
#   path: ${path.config}/modules.d/*.yml
#   reload.enabled: false
setup.template.enabled: true
setup.template.name: "filebeat-%{[agent.version]}"
setup.template.pattern: "filebeat-%{[agent.version]}-*" 
setup.template.settings:
  index.number_of_shards: 1
  
setup.kibana:
  host: "https://kibana-uow.1ez.xyz:443"
  username: "elastic"
  password: "whenguardian2021"

output.elasticsearch:
  hosts: ["elasticsearch-uow.1ez.xyz:443"]
  username: "elastic"
  password: "whenguardian2021"
  index: "filebeat-%{[agent.version]}-%{+yyyy.MM.dd}"
  template.enabled: true
  protocol: "https" 

processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~
  - drop_event:
      when:
        equals:
          index._type: "pcap_file"    