filebeat.inputs:
- type: log
  paths:
    - "/tshark/packets.json"
  document_type: "pcap_file"
  json.keys_under_root: true

- type: log
  paths:
    - "/var/log/apache2/*"
  fields:
    apache: true
  fields_under_root: true

- type: log
  paths:
    - "/var/log/suricata/eve.json"
    
  json.keys_under_root: true

- type: log
  paths:
    - "/var/log/suricata/fast.log"

- type: log
  paths:
    - "/var/log/mysql/*"
  fields:
    mysql: true
  fields_under_root: true

output.logstash:
  hosts: ["{{ LOGSTASH_URI }}:{{ LOGSTASH_PORT }}"]

processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~
  - drop_event:
      when:
        equals:
          index._type: "pcap_file"    
